module gifvault {
    requires java.base;
    requires java.logging;
    requires org.slf4j;
    requires org.apache.logging.log4j;
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.media;
    requires javafx.web;
    requires java.desktop;
    requires java.sql;
    requires fontawesomefx;
    requires com.jfoenix;
    requires org.controlsfx.controls;
    requires uk.co.caprica.vlcj;
    requires uk.co.caprica.vlcj.javafx;
    requires org.apache.commons.lang3;
    requires java.persistence;
    requires java.naming;
    requires java.xml;
    requires java.xml.bind;
    requires com.fasterxml.classmate;
    requires com.sun.xml.bind;
    requires net.bytebuddy;
    requires org.hibernate.orm.core;
    requires gson;
    requires org.apache.commons.io;
    requires java.curl;
    requires static lombok;
    requires giphy4j;

    opens com.vinberts.gifvault to javafx.fxml;
    opens com.vinberts.gifvault.controllers.gihpy to javafx.fxml;
    opens com.vinberts.gifvault.controllers.main to javafx.fxml;
    opens com.vinberts.gifvault.controllers.vault to javafx.fxml;
    opens com.vinberts.gifvault.controllers.about to javafx.fxml;
    opens com.vinberts.gifvault.controllers.settings to javafx.fxml;
    opens com.vinberts.gifvault.controllers.folders to javafx.fxml;
    opens com.vinberts.gifvault.data to org.hibernate.orm.core;
    exports com.vinberts.gifvault;
}
